//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Page.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurent
    {
        public int Sno { get; set; }
        public string Item { get; set; }
        public string Spice { get; set; }
        public Nullable<double> Price { get; set; }

        public string ImagePath { get; set; }
    }
}
